### PR TITLE
Dtcertmanager

### PR DESCRIPTION
**Pull request by casibbald**
Please merge, kindly remove the branch on merge

### CODE REVIEW

**Comment by Cellebyte** [comment]
I thougt you templated and tested if the configuration is the same.

**Comment by casibbald** [comment]
tested the chart produced from the branch, and its working.
Needs to be merged to release and the 'dtcertmanager' line removed from the ci branches

**Comment by Cellebyte** [comment]
@casibbald i diffed the to and they produce similar results.
Please go with the current cert-manager chart. As it is working as you expect it.

**Comment by casibbald** [comment]
Will get the CAPI stuff fully working and then come back to this after.

I do prefer to use upstream charts

**Comment by Cellebyte** [comment]
Its the upstream chart.

**Pull request closed without merging**
